version: 2
jobs:
  deploy:
    docker:
      - image: 'tomastomecek/rust:nightly'
        environment:
          CARGO_HOME: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          key: 'v1-cargo-crates-{{ checksum "Cargo.lock"}}'
      - run:
          name: Deploy Bootimage TODO!
          command: >-
            echo "need to install cargo-make and bootimage and deploy the
            artifact!"
      - save_cache:
          key: 'v1-cargo-crates-{{ checksum "Cargo.lock"}}'
          paths:
            - .cargo
  test:
    docker:
      - image: 'tomastomecek/rust:nightly'
        environment:
          CARGO_HOME: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          key: 'v1-cargo-crates-{{ checksum "Cargo.lock"}}'
      - run:
          name: Unit tests
          command: cargo test
      - save_cache:
          key: 'v1-cargo-crates-{{ checksum "Cargo.lock"}}'
          paths:
            - .cargo
  lint:
    docker:
      - image: 'tomastomecek/rust:clippy'
        environment:
          CARGO_HOME: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          key: 'v1-cargo-crates-{{ checksum "Cargo.lock"}}'
      - run:
          name: Linter (clippy)
          command: cargo test
      - save_cache:
          key: 'v1-cargo-crates-{{ checksum "Cargo.lock"}}'
          paths:
            - .cargo
workflows:
  version: 2
  lint_build_test:
    jobs:
      - lint
      - deploy
      - test
