version: 2
jobs:
  deploy:
    docker:
      - image: 'tomastomecek/rust:nightly'
        environment:
          CARGO_HOME: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          key: 'v2-cargo-crates-{{ checksum "Cargo.lock"}}'
      - run:
          name: Deploy Bootimage TODO!
          command: >-
            echo "need to install cargo-make and bootimage and deploy the
            artifact!"
      - save_cache:
          key: 'v2-cargo-crates-{{ checksum "Cargo.lock"}}'
          paths:
            - .cargo
  test:
    docker:
      - image: 'tomastomecek/rust:nightly'
        environment:
          CARGO_HOME: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          key: 'v2-cargo-crates-{{ checksum "Cargo.lock"}}'
      - run:
          name: Unit tests
          command: cargo test
      - save_cache:
          key: 'v2-cargo-crates-{{ checksum "Cargo.lock"}}'
          paths:
            - .cargo
workflows:
  version: 2
  deploy_test:
    jobs:
      - deploy
      - test
